/**
 * Privacy levels for analytics sharing
 */
export enum PrivacyLevel {
    /** All content and project names preserved */
    TRANSPARENT = 'transparent',

    /** Project names anonymized, content preserved */
    PROJECT_ANONYMOUS = 'project_anonymous',

    /** Sensitive info filtered, projects anonymized */
    HIGH_PRIVACY = 'high_privacy',

    /** Only statistics, no original content */
    STATISTICS_ONLY = 'statistics_only',
}

/**
 * Types of sensitive information to filter
 */
export enum SensitiveInfoType {
    API_KEY = 'api_key',
    TOKEN = 'token',
    PASSWORD = 'password',
    EMAIL = 'email',
    PHONE = 'phone',
    IP_ADDRESS = 'ip_address',
    FILE_PATH = 'file_path',
    URL = 'url',
    CREDIT_CARD = 'credit_card',
    CUSTOM = 'custom',
}

/**
 * Configuration for sensitive information filtering
 */
export interface SensitiveInfoConfig {
    /** Types of sensitive info to filter */
    types: SensitiveInfoType[];

    /** Custom regex patterns to filter */
    customPatterns?: RegExp[];

    /** Replacement strategy */
    replacementStrategy: 'redact' | 'mask' | 'generalize';

    /** Replacement text for 'redact' strategy */
    redactText?: string;
}

/**
 * Anonymization rules for projects
 */
export interface AnonymizationRules {
    /** Whether to anonymize project names */
    anonymizeProjects: boolean;

    /** Naming pattern for anonymized projects */
    namingPattern: 'sequential' | 'descriptive' | 'random';

    /** Whether to preserve technical details */
    preserveTechnicalDetails: boolean;

    /** Custom project name mappings */
    customMappings?: Map<string, string>;
}

/**
 * Content selection rules
 */
export interface ContentSelectionRules {
    /** Include only specific conversations */
    includeConversationIds?: string[];

    /** Exclude specific conversations */
    excludeConversationIds?: string[];

    /** Include only specific projects */
    includeProjects?: string[];

    /** Exclude specific projects */
    excludeProjects?: string[];

    /** Date range filter */
    dateRange?: {
        start?: Date;
        end?: Date;
    };

    /** Minimum complexity threshold */
    minComplexity?: number;

    /** Maximum complexity threshold */
    maxComplexity?: number;
}

/**
 * Complete privacy settings for analytics export
 */
export class PrivacySettings {
    constructor(
        public readonly level: PrivacyLevel = PrivacyLevel.HIGH_PRIVACY,
        public readonly sensitiveInfoConfig: SensitiveInfoConfig = PrivacySettings.getDefaultSensitiveConfig(),
        public readonly anonymizationRules: AnonymizationRules = PrivacySettings.getDefaultAnonymizationRules(),
        public readonly contentSelection: ContentSelectionRules = {},
        public readonly includeRawConversations: boolean = false,
        public readonly watermark: string = 'Generated by Show Me The Talk'
    ) {}

    /**
     * Create privacy settings for a specific level
     */
    static forLevel(level: PrivacyLevel): PrivacySettings {
        switch (level) {
            case PrivacyLevel.TRANSPARENT:
                return new PrivacySettings(
                    level,
                    {
                        types: [],
                        replacementStrategy: 'redact',
                    },
                    {
                        anonymizeProjects: false,
                        namingPattern: 'sequential',
                        preserveTechnicalDetails: true,
                    },
                    {},
                    true
                );

            case PrivacyLevel.PROJECT_ANONYMOUS:
                return new PrivacySettings(
                    level,
                    {
                        types: [SensitiveInfoType.API_KEY, SensitiveInfoType.TOKEN, SensitiveInfoType.PASSWORD],
                        replacementStrategy: 'redact',
                    },
                    {
                        anonymizeProjects: true,
                        namingPattern: 'descriptive',
                        preserveTechnicalDetails: true,
                    },
                    {},
                    true
                );

            case PrivacyLevel.HIGH_PRIVACY:
                return new PrivacySettings(
                    level,
                    PrivacySettings.getDefaultSensitiveConfig(),
                    {
                        anonymizeProjects: true,
                        namingPattern: 'sequential',
                        preserveTechnicalDetails: true,
                    },
                    {},
                    false
                );

            case PrivacyLevel.STATISTICS_ONLY:
                return new PrivacySettings(
                    level,
                    PrivacySettings.getDefaultSensitiveConfig(),
                    {
                        anonymizeProjects: true,
                        namingPattern: 'random',
                        preserveTechnicalDetails: false,
                    },
                    {},
                    false
                );
        }
    }

    /**
     * Get default sensitive info configuration
     */
    private static getDefaultSensitiveConfig(): SensitiveInfoConfig {
        return {
            types: [
                SensitiveInfoType.API_KEY,
                SensitiveInfoType.TOKEN,
                SensitiveInfoType.PASSWORD,
                SensitiveInfoType.EMAIL,
                SensitiveInfoType.PHONE,
                SensitiveInfoType.IP_ADDRESS,
                SensitiveInfoType.FILE_PATH,
            ],
            replacementStrategy: 'generalize',
            redactText: '[REDACTED]',
        };
    }

    /**
     * Get default anonymization rules
     */
    private static getDefaultAnonymizationRules(): AnonymizationRules {
        return {
            anonymizeProjects: true,
            namingPattern: 'sequential',
            preserveTechnicalDetails: true,
        };
    }

    /**
     * Check if a specific info type should be filtered
     */
    shouldFilterType(type: SensitiveInfoType): boolean {
        return this.sensitiveInfoConfig.types.includes(type);
    }

    /**
     * Get replacement text for filtered content
     */
    getReplacementText(type: SensitiveInfoType, originalText: string): string {
        switch (this.sensitiveInfoConfig.replacementStrategy) {
            case 'redact':
                return this.sensitiveInfoConfig.redactText || '[REDACTED]';
            case 'mask':
                return this.maskText(originalText);
            case 'generalize':
                return this.generalizeText(type);
        }
    }

    /**
     * Mask text (keep first and last char, mask middle)
     */
    private maskText(text: string): string {
        if (text.length <= 2) return '***';
        return text[0] + '*'.repeat(text.length - 2) + text[text.length - 1];
    }

    /**
     * Generalize text based on type
     */
    private generalizeText(type: SensitiveInfoType): string {
        switch (type) {
            case SensitiveInfoType.API_KEY:
                return '[API_KEY]';
            case SensitiveInfoType.TOKEN:
                return '[TOKEN]';
            case SensitiveInfoType.PASSWORD:
                return '[PASSWORD]';
            case SensitiveInfoType.EMAIL:
                return '[EMAIL]';
            case SensitiveInfoType.PHONE:
                return '[PHONE]';
            case SensitiveInfoType.IP_ADDRESS:
                return '[IP_ADDRESS]';
            case SensitiveInfoType.FILE_PATH:
                return '~/[PATH]';
            case SensitiveInfoType.URL:
                return '[URL]';
            case SensitiveInfoType.CREDIT_CARD:
                return '[CARD_NUMBER]';
            default:
                return '[REDACTED]';
        }
    }
}
