import { AnalyticsReport, AnalyticsInsight } from '../../../domain/models/analytics/AnalyticsReport.js';
import { WordCloudHtmlRenderer, WordCloudRenderOptions } from './WordCloudHtmlRenderer.js';
import { SemanticCluster } from '../../../domain/models/analytics/SemanticCluster.js';

/**
 * Dashboard theme options
 */
export type DashboardTheme = 'light' | 'dark' | 'auto';

/**
 * Dashboard rendering options
 */
export interface DashboardRenderOptions {
    /** Page title */
    title?: string;
    /** Include word cloud section */
    includeWordCloud?: boolean;
    /** Include tech stack section */
    includeTechStack?: boolean;
    /** Include task distribution section */
    includeTaskDistribution?: boolean;
    /** Include topic clusters section */
    includeTopicClusters?: boolean;
    /** Include timeline section */
    includeTimeline?: boolean;
    /** Include insights section */
    includeInsights?: boolean;
    /** Theme mode */
    theme?: DashboardTheme;
    /** Enable social sharing metadata */
    enableSocialSharing?: boolean;
    /** Custom branding/watermark */
    watermark?: string;
    /** Word cloud options */
    wordCloudOptions?: WordCloudRenderOptions;
}

interface HeroHighlight {
    icon: string;
    label: string;
    value: string;
    subtext?: string;
}

/**
 * Generates complete HTML dashboard for analytics reports
 * Creates an interactive, responsive dashboard with multiple visualization sections
 */
export class AnalyticsDashboardTemplate {
    private readonly options: Required<DashboardRenderOptions>;
    private readonly wordCloudRenderer: WordCloudHtmlRenderer;

    constructor(options: DashboardRenderOptions = {}) {
        this.options = {
            title: options.title ?? 'Claude Code Analytics Dashboard',
            includeWordCloud: options.includeWordCloud ?? true,
            includeTechStack: options.includeTechStack ?? true,
            includeTaskDistribution: options.includeTaskDistribution ?? true,
            includeTopicClusters: options.includeTopicClusters ?? true,
            includeTimeline: options.includeTimeline ?? true,
            includeInsights: options.includeInsights ?? true,
            theme: options.theme ?? 'auto',
            enableSocialSharing: options.enableSocialSharing ?? true,
            watermark: options.watermark ?? 'Generated by Show Me The Talk',
            wordCloudOptions: options.wordCloudOptions ?? {}
        };

        this.wordCloudRenderer = new WordCloudHtmlRenderer(this.options.wordCloudOptions);
    }

    /**
     * Shared empty-state renderer
     */
    private renderEmptyState(icon: string, title: string, description: string, action?: string): string {
        return `<div class="empty-state" role="status">
        <div class="empty-icon" aria-hidden="true">${this.escapeHtml(icon)}</div>
        <div class="empty-title">${this.escapeHtml(title)}</div>
        <div class="empty-description">${this.escapeHtml(description)}</div>
        ${action ? `<div class="empty-action">${this.escapeHtml(action)}</div>` : ''}
    </div>`;
    }

    /**
     * Render complete dashboard HTML
     */
    render(report: AnalyticsReport): string {
        return `<!DOCTYPE html>
<html lang="en" data-theme="${this.options.theme}">
<head>
    ${this.generateHead(report)}
</head>
<body>
    ${this.generateThemeToggle()}

    <!-- TIER 1: HERO (Above Fold) -->
    ${this.generateHeader(report)}
    ${report.wrappedStory ? this.generateWrappedStoryModal(report) : ''}

    <main class="dashboard-container">
        <!-- TIER 2: SOCIAL PROOF -->
        ${report.achievements ? this.generateAchievementsSection(report) : ''}
        ${report.heatmap ? this.generateHeatmapSection(report) : ''}

        <!-- TIER 3: IDENTITY -->
        ${this.options.includeTechStack ? this.generateTechStackSection(report) : ''}
        ${this.options.includeWordCloud ? this.generateWordCloudSection(report) : ''}

        <!-- TIER 4: DETAILED ANALYTICS (Collapsible) -->
        <details class="analytics-details" open>
            <summary class="analytics-summary">
                <i class="fas fa-chart-bar"></i> View Detailed Analytics
                <i class="fas fa-chevron-down summary-icon"></i>
            </summary>
            <div class="analytics-details-content">
                ${this.generateOverviewSection(report)}
                ${this.options.includeTaskDistribution ? this.generateTaskDistributionSection(report) : ''}
                ${this.options.includeTopicClusters ? this.generateTopicClustersSection(report) : ''}
                ${this.options.includeTimeline ? this.generateTimelineSection(report) : ''}
                ${this.options.includeInsights ? this.generateInsightsSection(report) : ''}
            </div>
        </details>
    </main>

    ${this.generateFooter()}
    ${this.generateScripts(report)}
</body>
</html>`;
    }

    /**
     * Generate HTML head with metadata and styles
     */
    private generateHead(report: AnalyticsReport): string {
        const socialMeta = this.options.enableSocialSharing
            ? this.generateSocialMetadata(report)
            : '';

        return `<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Analytics dashboard for Claude Code conversations">
    <title>${this.escapeHtml(this.options.title)}</title>
    ${socialMeta}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    ${this.generateStyles()}`;
    }

    /**
     * Generate social sharing metadata
     */
    private generateSocialMetadata(report: AnalyticsReport): string {
        const metadata = report.toShareableFormat().getSocialMetadata();
        return Object.entries(metadata)
            .map(([key, value]) => `<meta property="${key}" content="${this.escapeHtml(value)}">`)
            .join('\n    ');
    }

    /**
     * Generate comprehensive dashboard styles
     */
    private generateStyles(): string {
        return `<style>
        /* Professional Design System - Vercel/Linear/Observable Style */

        :root {
            /* Monochrome Palette - Grays */
            --gray-50: #fafafa;
            --gray-100: #f5f5f5;
            --gray-200: #e5e5e5;
            --gray-300: #d4d4d4;
            --gray-400: #a3a3a3;
            --gray-500: #737373;
            --gray-600: #525252;
            --gray-700: #404040;
            --gray-800: #262626;
            --gray-900: #171717;

            /* Primary Color - Single Accent */
            --color-primary: #0070f3;
            --color-primary-hover: #0061d5;
            --color-primary-light: #3291ff;

            /* Semantic Colors - Low Saturation */
            --color-success: #10b981;
            --color-warning: #f59e0b;
            --color-error: #ef4444;

            /* Surface Colors */
            --bg-page: #ffffff;
            --bg-surface: #fafafa;
            --bg-elevated: #ffffff;
            --bg-hover: #f5f5f5;

            /* Text Colors */
            --text-primary: #171717;
            --text-secondary: #737373;
            --text-tertiary: #a3a3a3;

            /* Borders */
            --border: #e5e5e5;
            --border-hover: #d4d4d4;
            --border-radius: 4px;

            /* Spacing - 4px base unit */
            --space-1: 4px;
            --space-2: 8px;
            --space-3: 12px;
            --space-4: 16px;
            --space-6: 24px;
            --space-8: 32px;
            --space-12: 48px;

            /* Typography */
            --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Inter', sans-serif;
            --font-mono: 'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', monospace;

            --text-xs: 0.75rem;
            --text-sm: 0.875rem;
            --text-base: 1rem;
            --text-lg: 1.125rem;
            --text-xl: 1.25rem;
            --text-2xl: 1.5rem;
            --text-3xl: 2rem;

            --leading-tight: 1.25;
            --leading-normal: 1.5;
            --leading-relaxed: 1.75;

            /* Shadow - Minimal */
            --shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
        }

        [data-theme="dark"] {
            --gray-50: #171717;
            --gray-100: #262626;
            --gray-200: #404040;
            --gray-300: #525252;
            --gray-400: #737373;
            --gray-500: #a3a3a3;
            --gray-600: #d4d4d4;
            --gray-700: #e5e5e5;
            --gray-800: #f5f5f5;
            --gray-900: #fafafa;

            --bg-page: #000000;
            --bg-surface: #111111;
            --bg-elevated: #171717;
            --bg-hover: #262626;

            --text-primary: #fafafa;
            --text-secondary: #a3a3a3;
            --text-tertiary: #737373;

            --border: #262626;
            --border-hover: #404040;

            --shadow: 0 0 0 1px rgba(255, 255, 255, 0.06);
        }

        @media (prefers-color-scheme: dark) {
            [data-theme="auto"] {
                --gray-50: #171717;
                --gray-100: #262626;
                --gray-200: #404040;
                --bg-page: #000000;
                --bg-surface: #111111;
                --bg-elevated: #171717;
                --text-primary: #fafafa;
                --text-secondary: #a3a3a3;
                --border: #262626;
            }
        }

        /* Reset */
        *, *::before, *::after {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: var(--font-sans);
            font-size: var(--text-base);
            line-height: var(--leading-normal);
            color: var(--text-primary);
            background: var(--bg-page);
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }

        /* Theme Toggle - Minimal */
        .theme-toggle {
            position: fixed;
            top: var(--space-4);
            right: var(--space-4);
            z-index: 1000;
            width: 36px;
            height: 36px;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 1px solid var(--border);
            background: var(--bg-elevated);
            cursor: pointer;
            transition: background-color 0.15s, border-color 0.15s;
        }

        .theme-toggle:hover {
            background: var(--bg-hover);
            border-color: var(--border-hover);
        }

        .theme-toggle i {
            font-size: var(--text-base);
            color: var(--text-secondary);
        }

        /* Header - Clean and Minimal */
        .dashboard-header {
            border-bottom: 1px solid var(--border);
            background: var(--bg-elevated);
            padding: var(--space-8) var(--space-4);
        }

        .dashboard-header h1 {
            font-size: var(--text-3xl);
            font-weight: 600;
            line-height: var(--leading-tight);
            letter-spacing: -0.02em;
            max-width: 1280px;
            margin: 0 auto;
        }

        .wrapped-button {
            margin-top: var(--space-4);
            padding: var(--space-3) var(--space-6);
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            border-radius: 50px;
            font-size: var(--text-lg);
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
        }

        .wrapped-button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.6);
        }

        .wrapped-button i {
            margin-right: var(--space-2);
        }

        .dashboard-header .subtitle {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            margin-top: var(--space-2);
            max-width: 1280px;
            margin-left: auto;
            margin-right: auto;
        }

        /* Hero Header - Growth-Hacking Design */
        .hero-header {
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%);
            color: white;
            text-align: center;
            position: relative;
            overflow: hidden;
        }

        .hero-header::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: radial-gradient(circle at 50% 50%, transparent 0%, rgba(0, 0, 0, 0.2) 100%);
            pointer-events: none;
        }

        .hero-content {
            position: relative;
            z-index: 1;
            padding: var(--space-8);
            max-width: 800px;
            margin: 0 auto;
        }

        .hero-year {
            font-size: 24px;
            font-weight: 300;
            letter-spacing: 2px;
            opacity: 0.9;
            margin-bottom: var(--space-3);
        }

        .hero-title {
            font-size: 72px;
            font-weight: 900;
            line-height: 1.1;
            margin: 0 0 var(--space-8);
            text-shadow: 0 2px 20px rgba(0, 0, 0, 0.3);
        }

        .hero-persona {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: var(--space-6);
            margin: var(--space-8) 0;
            padding: var(--space-6);
            background: rgba(255, 255, 255, 0.1);
            border: 2px solid rgba(255, 255, 255, 0.2);
            border-radius: 24px;
            backdrop-filter: blur(10px);
        }

        .hero-persona-emoji {
            font-size: 80px;
        }

        .hero-persona-text {
            text-align: left;
        }

        .hero-persona-label {
            font-size: 18px;
            opacity: 0.9;
            margin-bottom: 4px;
        }

        .hero-persona-name {
            font-size: 36px;
            font-weight: 900;
            margin-bottom: 8px;
        }

        .hero-mbti {
            font-size: 16px;
            opacity: 0.85;
            font-style: italic;
        }

        .hero-stat {
            margin: var(--space-8) 0;
        }

        .hero-stat-number {
            font-size: 128px;
            font-weight: 900;
            line-height: 1;
            margin-bottom: var(--space-2);
            text-shadow: 0 4px 30px rgba(0, 0, 0, 0.3);
        }

        .hero-stat-label {
            font-size: 24px;
            opacity: 0.95;
            font-weight: 500;
        }

        .hero-cta {
            margin-top: var(--space-8);
            padding: 24px 48px;
            background: white;
            color: #667eea;
            border: none;
            border-radius: 60px;
            font-size: 24px;
            font-weight: 700;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.3);
        }

        .hero-cta:hover {
            transform: translateY(-4px) scale(1.05);
            box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
        }

        .hero-cta i {
            margin-right: var(--space-3);
        }

        .hero-highlights {
            margin-top: var(--space-8);
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: var(--space-4);
        }

        .hero-highlight-card {
            display: flex;
            gap: var(--space-3);
            align-items: center;
            padding: var(--space-4);
            border-radius: 20px;
            background: rgba(255, 255, 255, 0.12);
            border: 1px solid rgba(255, 255, 255, 0.25);
            text-align: left;
        }

        .hero-highlight-icon {
            font-size: 2rem;
        }

        .hero-highlight-label {
            font-size: var(--text-xs);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            opacity: 0.8;
        }

        .hero-highlight-value {
            font-size: var(--text-xl);
            font-weight: 700;
        }

        .hero-highlight-subtext {
            font-size: var(--text-xs);
            opacity: 0.75;
        }

        .empty-state {
            border: 2px dashed var(--border);
            border-radius: 16px;
            padding: var(--space-8);
            text-align: center;
            background: var(--bg-elevated);
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: var(--space-3);
        }

        .empty-icon {
            font-size: 48px;
        }

        .empty-title {
            font-size: var(--text-xl);
            font-weight: 600;
        }

        .empty-description {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            max-width: 420px;
        }

        .empty-action {
            font-size: var(--text-xs);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            color: var(--text-tertiary);
        }

        .hero-scroll-hint {
            margin-top: var(--space-12);
            font-size: 32px;
            opacity: 0.7;
            animation: bounce 2s infinite;
        }

        @keyframes bounce {
            0%, 20%, 50%, 80%, 100% {
                transform: translateY(0);
            }
            40% {
                transform: translateY(-10px);
            }
            60% {
                transform: translateY(-5px);
            }
        }

        @media (max-width: 1024px) {
            .hero-header {
                min-height: 80vh;
                padding: var(--space-8) var(--space-4);
            }

            .hero-title {
                font-size: 56px;
            }

            .hero-persona {
                flex-direction: column;
                text-align: center;
            }
        }

        @media (max-width: 640px) {
            .hero-header {
                min-height: 55vh;
                padding: var(--space-6) var(--space-3);
            }

            .hero-content {
                padding: var(--space-4) var(--space-2);
            }

            .hero-title {
                font-size: 40px;
            }

            .hero-persona-emoji {
                font-size: 56px;
            }

            .hero-persona-name {
                font-size: 28px;
            }

            .hero-stat-number {
                font-size: 72px;
            }

            .hero-highlights {
                grid-template-columns: 1fr;
            }
        }

        @media (prefers-reduced-motion: reduce) {
            .hero-scroll-hint {
                animation: none;
            }

            .hero-cta,
            .hero-persona,
            .heatmap-cell,
            .achievement-card {
                transition: none;
            }
        }

        /* Container */
        .dashboard-container {
            max-width: 1280px;
            margin: 0 auto;
            padding: var(--space-6) var(--space-4);
        }

        /* Section */
        .section {
            margin-bottom: var(--space-12);
        }

        .section-header {
            display: flex;
            align-items: center;
            gap: var(--space-3);
            margin-bottom: var(--space-6);
            padding-bottom: var(--space-4);
            border-bottom: 1px solid var(--border);
        }

        .section-header i {
            font-size: var(--text-lg);
            color: var(--text-tertiary);
        }

        .section-header h2 {
            font-size: var(--text-xl);
            font-weight: 600;
            line-height: var(--leading-tight);
        }

        /* Collapsible Details Section */
        .analytics-details {
            margin-top: var(--space-12);
            border: 2px solid var(--border);
            border-radius: var(--border-radius);
            overflow: hidden;
        }

        .analytics-summary {
            padding: var(--space-6);
            background: var(--bg-elevated);
            cursor: pointer;
            user-select: none;
            display: flex;
            align-items: center;
            gap: var(--space-3);
            font-size: var(--text-lg);
            font-weight: 600;
            transition: all 0.3s;
        }

        .analytics-summary:hover {
            background: var(--bg-hover);
        }

        .analytics-summary i.fas.fa-chart-bar {
            color: var(--color-primary);
        }

        .summary-icon {
            margin-left: auto;
            transition: transform 0.3s;
        }

        .analytics-details[open] .summary-icon {
            transform: rotate(180deg);
        }

        .analytics-details-content {
            padding: var(--space-6);
            background: var(--bg-page);
        }

        /* Stats Grid - Information Dense */
        .overview-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1px;
            background: var(--border);
            border: 1px solid var(--border);
        }

        .stat-card {
            background: var(--bg-elevated);
            padding: var(--space-6);
            display: flex;
            flex-direction: column;
            gap: var(--space-2);
        }

        .stat-label {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            font-weight: 400;
        }

        .stat-value {
            font-size: 4rem;
            font-weight: 700;
            line-height: 1;
            letter-spacing: -0.04em;
            font-variant-numeric: tabular-nums;
            color: var(--text-primary);
        }

        .stat-meta {
            font-size: var(--text-xs);
            color: var(--text-tertiary);
        }

        /* Chart Container */
        .chart-container {
            position: relative;
            height: 400px;
            margin: var(--space-6) 0;
            background: var(--bg-elevated);
            padding: var(--space-4);
            border: 1px solid var(--border);
        }

        .chart-canvas {
            max-height: 100%;
        }

        /* Insights - Left Bar Style */
        .insights-grid {
            display: grid;
            gap: var(--space-4);
        }

        .insight-card {
            display: grid;
            grid-template-columns: 4px 1fr;
            gap: var(--space-4);
            background: var(--bg-elevated);
            border: 1px solid var(--border);
            overflow: hidden;
        }

        .insight-indicator {
            background: var(--color-primary);
        }

        .insight-card.high .insight-indicator {
            background: var(--color-error);
        }

        .insight-card.medium .insight-indicator {
            background: var(--color-warning);
        }

        .insight-card.low .insight-indicator {
            background: var(--color-success);
        }

        .insight-content {
            padding: var(--space-4);
        }

        .insight-header {
            display: flex;
            align-items: baseline;
            gap: var(--space-3);
            margin-bottom: var(--space-2);
        }

        .insight-badge {
            font-size: var(--text-xs);
            color: var(--text-tertiary);
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .insight-title {
            font-size: var(--text-lg);
            font-weight: 600;
            line-height: var(--leading-tight);
        }

        .insight-description {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            line-height: var(--leading-relaxed);
            margin-bottom: var(--space-3);
        }

        .insight-evidence {
            background: var(--bg-surface);
            padding: var(--space-3);
            font-size: var(--text-sm);
            color: var(--text-secondary);
            font-family: var(--font-mono);
        }

        .insight-evidence ul {
            list-style: disc;
            margin-left: var(--space-4);
        }

        .insight-evidence li {
            margin: var(--space-1) 0;
        }

        /* Clusters - Clean Card Grid */
        .clusters-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: var(--space-4);
        }

        .cluster-card {
            background: var(--bg-elevated);
            border: 1px solid var(--border);
            padding: var(--space-4);
        }

        .cluster-label {
            font-size: var(--text-lg);
            font-weight: 600;
            margin-bottom: var(--space-2);
        }

        .cluster-size {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            margin-bottom: var(--space-3);
        }

        .cluster-keywords {
            display: flex;
            flex-wrap: wrap;
            gap: var(--space-2);
        }

        .keyword-tag {
            padding: var(--space-1) var(--space-2);
            background: var(--bg-surface);
            border: 1px solid var(--border);
            font-size: var(--text-xs);
            color: var(--text-secondary);
        }

        /* Export Controls */
        .export-controls {
            display: flex;
            gap: var(--space-3);
            margin-top: var(--space-6);
        }

        .export-button {
            padding: var(--space-2) var(--space-4);
            border: 1px solid var(--border);
            background: var(--bg-elevated);
            color: var(--text-primary);
            font-size: var(--text-sm);
            font-weight: 500;
            cursor: pointer;
            transition: background-color 0.15s, border-color 0.15s;
            display: inline-flex;
            align-items: center;
            gap: var(--space-2);
        }

        .export-button:hover {
            background: var(--bg-hover);
            border-color: var(--border-hover);
        }

        /* Footer */
        .footer {
            text-align: center;
            padding: var(--space-8) var(--space-4);
            border-top: 1px solid var(--border);
            margin-top: var(--space-12);
        }

        .footer-logo {
            font-size: var(--text-base);
            font-weight: 500;
            color: var(--text-secondary);
        }

        .footer-links {
            display: flex;
            justify-content: center;
            gap: var(--space-4);
            margin-top: var(--space-3);
        }

        .footer-links a {
            color: var(--text-secondary);
            text-decoration: none;
            font-size: var(--text-sm);
            transition: color 0.15s;
        }

        .footer-links a:hover {
            color: var(--color-primary);
        }

        /* Responsive */
        @media (max-width: 768px) {
            .dashboard-header h1 {
                font-size: var(--text-2xl);
            }

            .overview-grid {
                grid-template-columns: 1fr;
            }

            .chart-container {
                height: 300px;
            }

            .clusters-grid {
                grid-template-columns: 1fr;
            }
        }

        /* Heatmap Styles */
        .heatmap-summary {
            display: grid;
            grid-template-columns: 2fr repeat(3, 1fr);
            gap: var(--space-4);
            margin-bottom: var(--space-6);
        }

        .streak-card {
            display: flex;
            align-items: center;
            gap: var(--space-4);
            background: var(--bg-elevated);
            border: 2px solid var(--border);
            padding: var(--space-6);
            transition: all 0.3s;
        }

        .streak-card.active {
            border-color: #f59e0b;
            background: linear-gradient(135deg, rgba(245, 158, 11, 0.1) 0%, rgba(245, 158, 11, 0.05) 100%);
        }

        .streak-icon {
            font-size: 3rem;
        }

        .streak-value {
            font-size: 3rem;
            font-weight: 700;
            line-height: 1;
            color: var(--text-primary);
        }

        .streak-label {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            margin-top: var(--space-1);
        }

        .streak-status {
            font-size: var(--text-xs);
            color: #f59e0b;
            font-weight: 600;
            margin-top: var(--space-1);
            text-transform: uppercase;
        }

        .heatmap-stat {
            display: flex;
            align-items: center;
            gap: var(--space-3);
            background: var(--bg-elevated);
            border: 1px solid var(--border);
            padding: var(--space-4);
        }

        .stat-icon {
            font-size: 1.5rem;
        }

        .stat-number {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--text-primary);
        }

        .stat-text {
            font-size: var(--text-xs);
            color: var(--text-secondary);
        }

        .heatmap-container {
            background: var(--bg-elevated);
            border: 1px solid var(--border);
            padding: var(--space-4);
            overflow-x: auto;
            min-height: 150px;
        }

        .heatmap-grid {
            display: inline-grid;
            grid-template-rows: repeat(7, 12px);
            grid-auto-flow: column;
            gap: 3px;
        }

        .heatmap-cell {
            width: 12px;
            height: 12px;
            border-radius: 2px;
            cursor: pointer;
            transition: all 0.2s;
        }

        .heatmap-cell[data-level="0"] { background: var(--gray-200); }
        .heatmap-cell[data-level="1"] { background: #9be9a8; }
        .heatmap-cell[data-level="2"] { background: #40c463; }
        .heatmap-cell[data-level="3"] { background: #30a14e; }
        .heatmap-cell[data-level="4"] { background: #216e39; }

        [data-theme="dark"] .heatmap-cell[data-level="0"] { background: var(--gray-200); }

        .heatmap-cell:hover {
            transform: scale(1.3);
            box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.2);
        }

        .heatmap-legend {
            display: flex;
            align-items: center;
            gap: var(--space-2);
            margin-top: var(--space-4);
            justify-content: flex-end;
        }

        .legend-label {
            font-size: var(--text-xs);
            color: var(--text-tertiary);
        }

        .legend-cell {
            width: 12px;
            height: 12px;
            border-radius: 2px;
        }

        .legend-cell[data-level="0"] { background: var(--gray-200); }
        .legend-cell[data-level="1"] { background: #9be9a8; }
        .legend-cell[data-level="2"] { background: #40c463; }
        .legend-cell[data-level="3"] { background: #30a14e; }
        .legend-cell[data-level="4"] { background: #216e39; }

        /* Achievements Styles */
        .achievements-summary {
            display: flex;
            justify-content: center;
            margin-bottom: var(--space-8);
        }

        .completion-card {
            text-align: center;
        }

        .completion-ring {
            width: 120px;
            height: 120px;
            margin: 0 auto var(--space-4);
            position: relative;
        }

        .completion-ring svg {
            transform: rotate(-90deg);
        }

        .ring-bg {
            fill: none;
            stroke: var(--border);
            stroke-width: 8;
        }

        .ring-progress {
            fill: none;
            stroke: var(--color-primary);
            stroke-width: 8;
            stroke-dasharray: 283;
            stroke-dashoffset: 283;
            transition: stroke-dashoffset 2s ease-out;
            stroke-linecap: round;
        }

        .completion-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .completion-percent {
            font-size: 2rem;
            font-weight: 700;
            color: var(--text-primary);
        }

        .completion-label {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            font-weight: 500;
        }

        .achievements-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: var(--space-4);
        }

        .achievement-card {
            display: flex;
            gap: var(--space-4);
            background: var(--bg-elevated);
            border: 2px solid var(--border);
            padding: var(--space-4);
            transition: all 0.3s;
        }

        .achievement-card.unlocked {
            border-color: var(--color-primary);
            box-shadow: 0 0 0 1px var(--color-primary);
        }

        .achievement-card.locked {
            opacity: 0.6;
        }

        .achievement-icon {
            font-size: 3rem;
            flex-shrink: 0;
            transition: filter 0.3s;
        }

        .achievement-icon.grayscale {
            filter: grayscale(100%);
        }

        .achievement-content {
            flex: 1;
        }

        .achievement-header {
            display: flex;
            align-items: baseline;
            gap: var(--space-2);
            margin-bottom: var(--space-2);
        }

        .achievement-name {
            font-size: var(--text-lg);
            font-weight: 600;
            color: var(--text-primary);
        }

        .achievement-rarity {
            font-size: var(--text-xs);
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .achievement-description {
            font-size: var(--text-sm);
            color: var(--text-secondary);
            margin-bottom: var(--space-3);
        }

        .achievement-progress {
            margin-top: var(--space-3);
        }

        .progress-bar {
            height: 6px;
            background: var(--border);
            border-radius: 3px;
            overflow: hidden;
            margin-bottom: var(--space-2);
        }

        .progress-fill {
            height: 100%;
            transition: width 1s ease-out;
        }

        .progress-text {
            font-size: var(--text-xs);
            color: var(--text-tertiary);
            font-weight: 500;
        }

        .achievement-criteria {
            font-size: var(--text-xs);
            color: var(--text-tertiary);
            font-style: italic;
            margin-top: var(--space-2);
        }

        /* Responsive - Heatmap & Achievements */
        @media (max-width: 768px) {
            .heatmap-summary {
                grid-template-columns: 1fr;
            }

            .heatmap-grid {
                grid-template-rows: repeat(7, 10px);
                gap: 2px;
            }

            .heatmap-cell {
                width: 10px;
                height: 10px;
            }

            .achievements-grid {
                grid-template-columns: 1fr;
            }
        }

        /* Wrapped Story Modal */
        .wrapped-modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 9999;
        }

        .wrapped-modal.active {
            display: block;
        }

        .wrapped-overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.95);
        }

        .wrapped-container {
            position: relative;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .wrapped-close {
            position: absolute;
            top: 20px;
            right: 20px;
            z-index: 10001;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            background: rgba(255, 255, 255, 0.2);
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .wrapped-close:hover {
            background: rgba(255, 255, 255, 0.3);
            transform: scale(1.1);
        }

        .wrapped-swiper {
            width: 100%;
            max-width: 450px;
            height: 100vh;
            max-height: 900px;
        }

        .story-card {
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 60px 40px;
            color: white;
            text-align: center;
        }

        .bg-gradient-blue { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }
        .bg-gradient-purple { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); }
        .bg-gradient-orange { background: linear-gradient(135deg, #fa709a 0%, #fee140 100%); }
        .bg-solid-dark { background: #1a1a2e; }
        .bg-solid-light { background: #ffffff; color: #1a1a2e; }

        .card-content {
            width: 100%;
        }

        .card-emoji { font-size: 80px; margin-bottom: 20px; }
        .card-title { font-size: 48px; font-weight: 700; margin-bottom: 16px; line-height: 1.2; }
        .card-title-small { font-size: 32px; font-weight: 700; margin-bottom: 32px; }
        .card-subtitle { font-size: 24px; opacity: 0.9; margin-bottom: 24px; }
        .card-number { font-size: 96px; font-weight: 900; margin: 32px 0; }
        .card-number-huge { font-size: 128px; font-weight: 900; margin: 48px 0; }
        .card-label { font-size: 20px; opacity: 0.8; }
        .card-label-top { font-size: 18px; opacity: 0.7; margin-bottom: 16px; }
        .card-context { font-size: 28px; opacity: 0.95; font-weight: 600; }

        .wrapped-word-cloud {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            gap: 12px;
            margin-top: 40px;
        }

        .wrapped-word {
            display: inline-block;
            font-weight: 600;
            opacity: 0.9;
        }

        .streak-display { margin: 40px 0; }
        .streak-icon-big { font-size: 100px; }
        .streak-number { font-size: 80px; font-weight: 900; margin: 20px 0; }
        .streak-text { font-size: 24px; opacity: 0.9; }
        .streak-active { font-size: 20px; color: #fbbf24; font-weight: 600; margin-top: 12px; }

        .stats-row {
            display: flex;
            justify-content: center;
            gap: 48px;
            margin-top: 48px;
        }

        .stat-item { text-align: center; }
        .stat-num { font-size: 48px; font-weight: 900; }
        .stat-label { font-size: 16px; opacity: 0.8; margin-top: 8px; }

        .tech-list { margin-top: 40px; text-align: left; max-width: 350px; margin-left: auto; margin-right: auto; }
        .tech-item {
            display: flex;
            align-items: center;
            gap: 16px;
            padding: 16px 0;
            border-bottom: 1px solid rgba(255, 255, 255, 0.2);
        }

        .tech-rank { font-size: 28px; width: 40px; }
        .tech-name { flex: 1; font-size: 24px; font-weight: 600; }
        .tech-count { font-size: 20px; opacity: 0.7; }

        .completion-big { font-size: 96px; font-weight: 900; margin: 32px 0; }
        .badges-showcase { display: flex; justify-content: center; gap: 32px; margin-top: 40px; flex-wrap: wrap; }
        .badge-item { text-align: center; }
        .badge-icon { font-size: 64px; }
        .badge-name { font-size: 16px; margin-top: 12px; opacity: 0.9; }

        .persona-emoji { font-size: 100px; margin-bottom: 24px; }
        .persona-name { font-size: 42px; font-weight: 900; margin: 24px 0; }
        .mbti-badge {
            display: inline-block;
            padding: 12px 24px;
            margin: 16px 0 24px;
            background: rgba(255, 255, 255, 0.15);
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-radius: 12px;
            backdrop-filter: blur(10px);
        }
        .mbti-type {
            font-size: 32px;
            font-weight: 900;
            letter-spacing: 4px;
            margin-right: 12px;
        }
        .mbti-desc {
            font-size: 16px;
            opacity: 0.85;
            font-style: italic;
        }
        .persona-description { font-size: 20px; opacity: 0.9; margin-bottom: 32px; }
        .persona-traits { list-style: none; text-align: left; max-width: 320px; margin: 0 auto; }
        .persona-traits li { font-size: 18px; padding: 12px 0; border-bottom: 1px solid rgba(255, 255, 255, 0.2); }

        .share-emoji { font-size: 80px; margin: 32px 0; }
        .share-cta { font-size: 22px; opacity: 0.9; margin-bottom: 40px; }
        .share-buttons { display: flex; flex-direction: column; gap: 16px; max-width: 300px; margin: 0 auto; }
        .share-btn {
            padding: 16px 24px;
            border: 2px solid rgba(255, 255, 255, 0.3);
            background: rgba(255, 255, 255, 0.1);
            color: white;
            font-size: 18px;
            font-weight: 600;
            border-radius: 50px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .share-btn:hover { background: rgba(255, 255, 255, 0.2); transform: scale(1.05); }
        .share-hashtag { font-size: 16px; opacity: 0.7; margin-top: 32px; }

        .wrapped-nav {
            position: absolute;
            bottom: 40px;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            gap: 20px;
            z-index: 10001;
        }

        .nav-prev, .nav-next {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background: rgba(255, 255, 255, 0.2);
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .nav-prev:hover, .nav-next:hover {
            background: rgba(255, 255, 255, 0.3);
            transform: scale(1.1);
        }

        .swiper-pagination-bullet {
            background: white;
            opacity: 0.5;
        }

        .swiper-pagination-bullet-active {
            opacity: 1;
        }

        /* Print Styles */
        @media print {
            .theme-toggle,
            .export-controls {
                display: none;
            }

            body {
                background: white;
            }

            .section {
                break-inside: avoid;
            }
        }
    </style>`;
    }

    /**
     * Generate theme toggle button
     */
    private generateThemeToggle(): string {
        return `<button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle theme">
        <i class="fas fa-moon"></i>
    </button>`;
    }

    /**
     * Generate header section
     */
    private generateHeader(report: AnalyticsReport): string {
        const hasWrapped = !!report.wrappedStory;
        const persona = report.persona;
        const stats = report.statistics;
        const year = new Date().getFullYear();
        const heroHighlights = this.generateHeroHighlights(report);

        // Hero-first design (Spotify Wrapped style)
        if (hasWrapped && persona) {
            return `<header class="hero-header">
        <div class="hero-content">
            <div class="hero-year">${year}</div>
            <h1 class="hero-title">Your Coding Year</h1>
            <div class="hero-persona">
                <span class="hero-persona-emoji">${persona.emoji}</span>
                <div class="hero-persona-text">
                    <div class="hero-persona-label">You are a</div>
                    <div class="hero-persona-name">${this.escapeHtml(persona.name)}</div>
                    <div class="hero-mbti">${this.escapeHtml(persona.mbti)} · ${this.escapeHtml(persona.mbtiDescription)}</div>
                </div>
            </div>
            <div class="hero-stat">
                <div class="hero-stat-number" data-countup="${stats.totalConversations}">0</div>
                <div class="hero-stat-label">Conversations with Claude</div>
            </div>
            ${heroHighlights}
            <button class="hero-cta" onclick="openWrappedStory()" aria-label="Open Wrapped Story modal">
                <i class="fas fa-sparkles"></i> View Your Wrapped Story
            </button>
            <div class="hero-scroll-hint">
                <i class="fas fa-chevron-down"></i>
            </div>
        </div>
    </header>`;
        }

        // Fallback: classic header
        return `<header class="dashboard-header">
        <h1><i class="fas fa-chart-line"></i> ${this.escapeHtml(this.options.title)}</h1>
        <div class="subtitle">
            ${this.escapeHtml(report.getSummary().split('\n')[0])}
        </div>
        ${hasWrapped ? `<button class="wrapped-button" onclick="openWrappedStory()">
            <i class="fas fa-sparkles"></i> View Your Wrapped
        </button>` : ''}
    </header>`;
    }

    private generateHeroHighlights(report: AnalyticsReport): string {
        const highlights = this.buildHeroHighlights(report);
        if (!highlights.length) {
            return '';
        }

        const cards = highlights.map(highlight => `
            <div class="hero-highlight-card" role="listitem">
                <div class="hero-highlight-icon" aria-hidden="true">${this.escapeHtml(highlight.icon)}</div>
                <div>
                    <div class="hero-highlight-label">${this.escapeHtml(highlight.label)}</div>
                    <div class="hero-highlight-value">${this.escapeHtml(highlight.value)}</div>
                    ${highlight.subtext ? `<div class="hero-highlight-subtext">${this.escapeHtml(highlight.subtext)}</div>` : ''}
                </div>
            </div>
        `).join('');

        return `<div class="hero-highlights" role="list">${cards}</div>`;
    }

    private buildHeroHighlights(report: AnalyticsReport): HeroHighlight[] {
        const highlights: HeroHighlight[] = [];
        const stats = report.statistics;

        if (report.heatmap) {
            const { streak, stats: heatmapStats } = report.heatmap;
            highlights.push({
                icon: '🔥',
                label: 'Longest Streak',
                value: `${streak.longestStreak} days`,
                subtext: streak.isActiveStreak ? 'Active right now' : 'Best run'
            });

            highlights.push({
                icon: '📅',
                label: 'Active Days',
                value: `${heatmapStats.activeDays}`,
                subtext: 'last 12 months'
            });
        }

        const averageMessages = stats.averageMessagesPerConversation;
        const averageValue = Number.isInteger(averageMessages)
            ? `${averageMessages}`
            : averageMessages.toFixed(1);
        highlights.push({
            icon: '💬',
            label: 'Avg Messages',
            value: averageValue,
            subtext: 'per conversation'
        });

        const [topTech] = report.getMostUsedTechnologies(1);
        if (topTech) {
            highlights.push({
                icon: '🛠️',
                label: 'Top Stack',
                value: topTech.tech,
                subtext: `${topTech.count} mentions`
            });
        }

        if (report.achievements) {
            highlights.push({
                icon: '🏅',
                label: 'Badges',
                value: `${report.achievements.totalUnlocked}`,
                subtext: `of ${report.achievements.achievements.length}`
            });
        }

        return highlights.slice(0, 4);
    }

    /**
     * Generate overview statistics section
     */
    private generateOverviewSection(report: AnalyticsReport): string {
        const stats = report.statistics;
        const dateRange = `${stats.dateRange.start.toLocaleDateString()} - ${stats.dateRange.end.toLocaleDateString()}`;

        return `<section class="section overview-section">
        <div class="section-header">
            <i class="fas fa-chart-pie"></i>
            <h2>Overview</h2>
        </div>
        <div class="overview-grid">
            <div class="stat-card">
                <div class="stat-label"><i class="fas fa-comments"></i> Conversations</div>
                <div class="stat-value" data-countup="${stats.totalConversations}">0</div>
                <div class="stat-meta">Keep going! 🚀</div>
            </div>
            <div class="stat-card">
                <div class="stat-label"><i class="fas fa-message"></i> Messages</div>
                <div class="stat-value" data-countup="${stats.totalMessages}">0</div>
                <div class="stat-meta">Every conversation counts</div>
            </div>
            <div class="stat-card">
                <div class="stat-label"><i class="fas fa-font"></i> Total Words</div>
                <div class="stat-value" data-countup="${stats.totalWords}">0</div>
                <div class="stat-meta">That's a lot of thinking!</div>
            </div>
            <div class="stat-card">
                <div class="stat-label"><i class="fas fa-chart-line"></i> Avg Messages/Conv</div>
                <div class="stat-value" data-countup="${stats.averageMessagesPerConversation}" data-decimals="1">0</div>
                <div class="stat-meta">Deep conversations ✨</div>
            </div>
            <div class="stat-card">
                <div class="stat-label"><i class="fas fa-calendar"></i> Date Range</div>
                <div class="stat-value" style="font-size: 1.2rem;">${this.escapeHtml(dateRange)}</div>
                <div class="stat-meta">Your journey so far</div>
            </div>
        </div>
    </section>`;
    }

    /**
     * Generate word cloud section
     */
    private generateWordCloudSection(report: AnalyticsReport): string {
        const words = report.wordCloud?.words ?? [];
        const topWords = words.slice(0, 50);

        if (topWords.length === 0) {
            const emptyState = this.renderEmptyState(
                '☁️',
                'Word Cloud Not Ready Yet',
                'We need at least one conversation to highlight your most used topics and technologies.',
                'Add conversations and regenerate this dashboard to unlock the visualization.'
            );
            return `<section class="section word-cloud-section">
        <div class="section-header">
            <i class="fas fa-cloud"></i>
            <h2>Word Cloud</h2>
        </div>
        ${emptyState}
    </section>`;
        }

        // Generate embedded word cloud HTML (simplified inline version)
        const wordsJson = JSON.stringify(topWords.map(w => ({
            text: w.text,
            size: Math.max(12, Math.min(60, w.weight * 1000)),
            weight: w.weight
        })));

        return `<section class="section word-cloud-section">
        <div class="section-header">
            <i class="fas fa-cloud"></i>
            <h2>Word Cloud</h2>
        </div>
        <div class="export-controls" style="margin-bottom: 16px;">
            <button class="export-button theme-btn" data-theme="tableau10" onclick="changeWordCloudTheme('tableau10')">
                <i class="fas fa-palette"></i> Vibrant
            </button>
            <button class="export-button theme-btn" data-theme="gradient" onclick="changeWordCloudTheme('gradient')">
                <i class="fas fa-fill-drip"></i> Gradient
            </button>
            <button class="export-button theme-btn" data-theme="monochrome" onclick="changeWordCloudTheme('monochrome')">
                <i class="fas fa-adjust"></i> Monochrome
            </button>
        </div>
        <div class="chart-container">
            <canvas id="wordCloudCanvas" class="chart-canvas"></canvas>
        </div>
        <div class="export-controls">
            <button class="export-button" onclick="exportWordCloud()">
                <i class="fas fa-download"></i> Export Word Cloud
            </button>
        </div>
        <script>
            window.wordCloudData = ${wordsJson};
            window.currentWordCloudTheme = 'tableau10';
        </script>
    </section>`;
    }

    /**
     * Generate tech stack section with radar/bar chart
     */
    private generateTechStackSection(report: AnalyticsReport): string {
        const topTech = report.getMostUsedTechnologies(10);
        const techData = JSON.stringify({
            labels: topTech.map(t => t.tech),
            data: topTech.map(t => t.count)
        });

        return `<section class="section tech-stack-section">
        <div class="section-header">
            <i class="fas fa-code"></i>
            <h2>Technology Stack</h2>
        </div>
        <div class="chart-container">
            <canvas id="techStackChart" class="chart-canvas"></canvas>
        </div>
        <script>
            window.techStackData = ${techData};
        </script>
    </section>`;
    }

    /**
     * Generate task distribution section with pie chart
     */
    private generateTaskDistributionSection(report: AnalyticsReport): string {
        const taskDist = report.taskTypeClusters.getDistribution();
        const taskData = JSON.stringify({
            labels: Array.from(taskDist.keys()),
            data: Array.from(taskDist.values())
        });

        return `<section class="section task-distribution-section">
        <div class="section-header">
            <i class="fas fa-tasks"></i>
            <h2>Task Distribution</h2>
        </div>
        <div class="chart-container">
            <canvas id="taskDistributionChart" class="chart-canvas"></canvas>
        </div>
        <script>
            window.taskDistributionData = ${taskData};
        </script>
    </section>`;
    }

    /**
     * Generate topic clusters section
     */
    private generateTopicClustersSection(report: AnalyticsReport): string {
        const topClusters = report.topicClusters.getLargestClusters(12);
        const clustersHtml = topClusters.map(cluster => {
            const keywords = cluster.getTopKeywords(8);
            return `<div class="cluster-card">
                <div class="cluster-label">${this.escapeHtml(cluster.label)}</div>
                <div class="cluster-size">${cluster.getSize()} conversations</div>
                <div class="cluster-keywords">
                    ${keywords.map(kw => `<span class="keyword-tag">${this.escapeHtml(kw)}</span>`).join('')}
                </div>
            </div>`;
        }).join('');

        return `<section class="section topic-clusters-section">
        <div class="section-header">
            <i class="fas fa-sitemap"></i>
            <h2>Topic Clusters</h2>
        </div>
        <div class="clusters-grid">
            ${clustersHtml}
        </div>
    </section>`;
    }

    /**
     * Generate timeline evolution section
     */
    private generateTimelineSection(report: AnalyticsReport): string {
        const timelineData = report.timeline.map(point => ({
            date: point.date.toISOString().split('T')[0],
            conversations: point.conversationCount,
            messages: point.messageCount
        }));

        const timelineJson = JSON.stringify({
            labels: timelineData.map(t => t.date),
            conversations: timelineData.map(t => t.conversations),
            messages: timelineData.map(t => t.messages)
        });

        return `<section class="section timeline-section">
        <div class="section-header">
            <i class="fas fa-timeline"></i>
            <h2>Activity Timeline</h2>
        </div>
        <div class="chart-container">
            <canvas id="timelineChart" class="chart-canvas"></canvas>
        </div>
        <script>
            window.timelineData = ${timelineJson};
        </script>
    </section>`;
    }

    /**
     * Generate insights section
     */
    private generateInsightsSection(report: AnalyticsReport): string {
        const insights = report.insights;
        const insightsHtml = insights.map(insight => {
            const evidenceHtml = insight.evidence.length > 0
                ? `<div class="insight-evidence">
                    <strong>Evidence:</strong>
                    <ul>
                        ${insight.evidence.map(e => `<li>${this.escapeHtml(e)}</li>`).join('')}
                    </ul>
                   </div>`
                : '';

            return `<div class="insight-card ${insight.importance}">
                <div class="insight-indicator"></div>
                <div class="insight-content">
                    <div class="insight-header">
                        <span class="insight-badge">${insight.importance.toUpperCase()}</span>
                        <div class="insight-title">${this.escapeHtml(insight.title)}</div>
                    </div>
                    <div class="insight-description">${this.escapeHtml(insight.description)}</div>
                    ${evidenceHtml}
                </div>
            </div>`;
        }).join('');

        return `<section class="section insights-section">
        <div class="section-header">
            <i class="fas fa-lightbulb"></i>
            <h2>Key Insights</h2>
        </div>
        <div class="insights-grid">
            ${insightsHtml}
        </div>
    </section>`;
    }

    /**
     * Generate conversation heatmap section (GitHub-style)
     */
    private generateHeatmapSection(report: AnalyticsReport): string {
        if (!report.heatmap) return '';

        const { cells, streak, stats } = report.heatmap;

        const cellsJson = JSON.stringify(cells);
        const hasActivity = cells.some(cell => cell.count > 0);
        const summaryHtml = hasActivity
            ? `<div class="heatmap-summary">
                <div class="streak-card ${streak.isActiveStreak ? 'active' : ''}">
                    <div class="streak-icon">🔥</div>
                    <div class="streak-content">
                        <div class="streak-value">${streak.currentStreak}</div>
                        <div class="streak-label">Day${streak.currentStreak !== 1 ? 's' : ''} Streak</div>
                        ${streak.isActiveStreak ? '<div class="streak-status">Active Today!</div>' : ''}
                    </div>
                </div>
                <div class="heatmap-stat">
                    <div class="stat-icon">📅</div>
                    <div class="stat-content">
                        <div class="stat-number">${stats.activeDays}</div>
                        <div class="stat-text">Active Days</div>
                    </div>
                </div>
                <div class="heatmap-stat">
                    <div class="stat-icon">🏆</div>
                    <div class="stat-content">
                        <div class="stat-number">${streak.longestStreak}</div>
                        <div class="stat-text">Longest Streak</div>
                    </div>
                </div>
                <div class="heatmap-stat">
                    <div class="stat-icon">⚡</div>
                    <div class="stat-content">
                        <div class="stat-number">${stats.maxDayCount}</div>
                        <div class="stat-text">Most in One Day</div>
                    </div>
                </div>
            </div>
            <div class="heatmap-container" id="heatmapContainer"></div>
            <div class="heatmap-legend">
                <span class="legend-label">Less</span>
                <div class="legend-cell" data-level="0"></div>
                <div class="legend-cell" data-level="1"></div>
                <div class="legend-cell" data-level="2"></div>
                <div class="legend-cell" data-level="3"></div>
                <div class="legend-cell" data-level="4"></div>
                <span class="legend-label">More</span>
            </div>
            <script>
                window.heatmapData = ${cellsJson};
            </script>`
            : this.renderEmptyState(
                '🌱',
                'Heatmap Awaits Your First Conversation',
                'Once you start chatting with Claude, your year-long contribution grid will light up with activity.',
                'Regenerate this report after you have at least one conversation.'
            );

        return `<section class="section heatmap-section">
        <div class="section-header">
            <i class="fas fa-fire"></i>
            <h2>Conversation Heatmap</h2>
        </div>
        ${summaryHtml}
    </section>`;
    }

    /**
     * Generate achievements section
     */
    private generateAchievementsSection(report: AnalyticsReport): string {
        if (!report.achievements) return '';

        const { achievements, totalUnlocked, completionPercentage } = report.achievements;

        // Sort: unlocked first, then by rarity
        const rarityOrder = { legendary: 0, epic: 1, rare: 2, common: 3 };
        const sorted = [...achievements].sort((a, b) => {
            if (a.unlocked !== b.unlocked) return a.unlocked ? -1 : 1;
            return rarityOrder[a.rarity] - rarityOrder[b.rarity];
        });

        const achievementsHtml = sorted.map(achievement => {
            const rarityColors = {
                common: '#10b981',
                rare: '#3b82f6',
                epic: '#a855f7',
                legendary: '#f59e0b'
            };
            const rarityColor = rarityColors[achievement.rarity];
            const progressPercent = Math.round(achievement.progress * 100);

            return `<div class="achievement-card ${achievement.unlocked ? 'unlocked' : 'locked'}" data-rarity="${achievement.rarity}">
                <div class="achievement-icon ${achievement.unlocked ? '' : 'grayscale'}">${achievement.icon}</div>
                <div class="achievement-content">
                    <div class="achievement-header">
                        <h3 class="achievement-name">${this.escapeHtml(achievement.name)}</h3>
                        <span class="achievement-rarity" style="color: ${rarityColor};">${achievement.rarity}</span>
                    </div>
                    <p class="achievement-description">${this.escapeHtml(achievement.description)}</p>
                    ${!achievement.unlocked ? `
                        <div class="achievement-progress">
                            <div class="progress-bar">
                                <div class="progress-fill" style="width: ${progressPercent}%; background: ${rarityColor};"></div>
                            </div>
                            <span class="progress-text">${progressPercent}%</span>
                        </div>
                        <p class="achievement-criteria">${this.escapeHtml(achievement.criteria)}</p>
                    ` : ''}
                </div>
            </div>`;
        }).join('');

        return `<section class="section achievements-section">
        <div class="section-header">
            <i class="fas fa-trophy"></i>
            <h2>Achievements</h2>
        </div>
        <div class="achievements-summary">
            <div class="completion-card">
                <div class="completion-ring">
                    <svg viewBox="0 0 100 100">
                        <circle cx="50" cy="50" r="45" class="ring-bg"></circle>
                        <circle cx="50" cy="50" r="45" class="ring-progress"
                                style="stroke-dashoffset: ${283 - (283 * completionPercentage / 100)};"></circle>
                    </svg>
                    <div class="completion-text">
                        <span class="completion-percent">${Math.round(completionPercentage)}%</span>
                    </div>
                </div>
                <div class="completion-label">${totalUnlocked}/${achievements.length} Unlocked</div>
            </div>
        </div>
        <div class="achievements-grid">
            ${achievementsHtml}
        </div>
    </section>`;
    }

    /**
     * Generate Wrapped Story modal
     */
    private generateWrappedStoryModal(report: AnalyticsReport): string {
        if (!report.wrappedStory || !report.persona) return '';

        const cardsHtml = report.wrappedStory.map((card, index) => {
            return this.generateStoryCard(card, report);
        }).join('');

        const storyData = JSON.stringify(report.wrappedStory);

        return `<div class="wrapped-modal" id="wrappedModal">
        <div class="wrapped-overlay"></div>
        <div class="wrapped-container">
            <button class="wrapped-close" onclick="closeWrappedStory()">
                <i class="fas fa-times"></i>
            </button>
            <div class="swiper wrapped-swiper">
                <div class="swiper-wrapper">
                    ${cardsHtml}
                </div>
                <div class="swiper-pagination"></div>
            </div>
            <div class="wrapped-nav">
                <button class="nav-prev" onclick="wrappedSwiper.slidePrev()">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <button class="nav-next" onclick="wrappedSwiper.slideNext()">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
        </div>
        <script>
            window.wrappedStoryData = ${storyData};
        </script>
    </div>`;
    }

    /**
     * Generate individual story card
     */
    private generateStoryCard(card: any, report: AnalyticsReport): string {
        const bgClass = `bg-${card.theme}`;

        let contentHtml = '';

        switch (card.content.type) {
            case 'welcome':
                contentHtml = `
                    <div class="card-emoji">🎉</div>
                    <h1 class="card-title">${this.escapeHtml(card.title)}</h1>
                    <p class="card-subtitle">${this.escapeHtml(card.subtitle || '')}</p>
                    <div class="card-number">${card.content.totalConversations}</div>
                    <p class="card-label">Conversations</p>
                `;
                break;

            case 'big_number':
                contentHtml = `
                    <p class="card-label-top">${this.escapeHtml(card.content.label)}</p>
                    <div class="card-number-huge">${card.content.number}</div>
                    <p class="card-context">${this.escapeHtml(card.content.context)}</p>
                `;
                break;

            case 'word_cloud':
                const wordsHtml = card.content.words.slice(0, 15).map((w: any) =>
                    `<span class="wrapped-word" style="font-size: ${w.size}%">${this.escapeHtml(w.text)}</span>`
                ).join(' ');
                contentHtml = `
                    <h2 class="card-title-small">${this.escapeHtml(card.title)}</h2>
                    <div class="wrapped-word-cloud">${wordsHtml}</div>
                `;
                break;

            case 'heatmap':
                contentHtml = `
                    <h2 class="card-title-small">${this.escapeHtml(card.title)}</h2>
                    <div class="streak-display">
                        <div class="streak-icon-big">🔥</div>
                        <div class="streak-number">${card.content.currentStreak}</div>
                        <p class="streak-text">Day${card.content.currentStreak !== 1 ? 's' : ''} Streak</p>
                        ${card.content.isActiveStreak ? '<p class="streak-active">Active Today!</p>' : ''}
                    </div>
                    <div class="stats-row">
                        <div class="stat-item">
                            <div class="stat-num">${card.content.longestStreak}</div>
                            <div class="stat-label">Longest</div>
                        </div>
                        <div class="stat-item">
                            <div class="stat-num">${card.content.activeDays}</div>
                            <div class="stat-label">Active Days</div>
                        </div>
                    </div>
                `;
                break;

            case 'tech_stack':
                const techHtml = card.content.technologies.map((t: any) => {
                    const medals = ['🥇', '🥈', '🥉'];
                    const medal = t.rank <= 3 ? medals[t.rank - 1] : `${t.rank}.`;
                    return `
                        <div class="tech-item">
                            <span class="tech-rank">${medal}</span>
                            <span class="tech-name">${this.escapeHtml(t.name)}</span>
                            <span class="tech-count">${t.count}</span>
                        </div>
                    `;
                }).join('');
                contentHtml = `
                    <h2 class="card-title-small">${this.escapeHtml(card.title)}</h2>
                    <div class="tech-list">${techHtml}</div>
                `;
                break;

            case 'achievements':
                const badgesHtml = card.content.highlights.map((a: any) =>
                    `<div class="badge-item">
                        <div class="badge-icon">${a.icon}</div>
                        <div class="badge-name">${this.escapeHtml(a.name)}</div>
                    </div>`
                ).join('');
                contentHtml = `
                    <h2 class="card-title-small">${this.escapeHtml(card.title)}</h2>
                    <div class="completion-big">${Math.round((card.content.unlockedCount / card.content.totalCount) * 100)}%</div>
                    <p class="card-subtitle">${card.content.unlockedCount} of ${card.content.totalCount} unlocked</p>
                    <div class="badges-showcase">${badgesHtml}</div>
                `;
                break;

            case 'persona':
                const persona = card.content.persona;
                const traitsHtml = persona.traits.slice(0, 4).map((t: string) =>
                    `<li>${this.escapeHtml(t)}</li>`
                ).join('');
                contentHtml = `
                    <div class="persona-emoji">${persona.emoji}</div>
                    <h2 class="card-title-small">You are a</h2>
                    <h1 class="persona-name">${this.escapeHtml(persona.name)}</h1>
                    <div class="mbti-badge">
                        <span class="mbti-type">${this.escapeHtml(persona.mbti)}</span>
                        <span class="mbti-desc">${this.escapeHtml(persona.mbtiDescription)}</span>
                    </div>
                    <p class="persona-description">${this.escapeHtml(persona.description)}</p>
                    <ul class="persona-traits">${traitsHtml}</ul>
                `;
                break;

            case 'share':
                contentHtml = `
                    <h2 class="card-title-small">${this.escapeHtml(card.title)}</h2>
                    <div class="share-emoji">✨</div>
                    <p class="share-cta">${this.escapeHtml(card.content.cta)}</p>
                    <div class="share-buttons">
                        <button class="share-btn share-twitter" onclick="shareToTwitter()">
                            <i class="fab fa-twitter"></i> Twitter
                        </button>
                        <button class="share-btn share-linkedin" onclick="shareToLinkedIn()">
                            <i class="fab fa-linkedin"></i> LinkedIn
                        </button>
                        <button class="share-btn share-download" onclick="downloadWrapped()">
                            <i class="fas fa-download"></i> Download
                        </button>
                    </div>
                    <p class="share-hashtag">${this.escapeHtml(card.content.hashtag)}</p>
                `;
                break;
        }

        return `<div class="swiper-slide">
            <div class="story-card ${bgClass}">
                <div class="card-content">
                    ${contentHtml}
                </div>
            </div>
        </div>`;
    }

    /**
     * Generate footer with watermark
     */
    private generateFooter(): string {
        return `<footer class="footer">
        <div class="footer-logo">${this.escapeHtml(this.options.watermark)}</div>
        <p>Analytics report generated on ${new Date().toLocaleDateString()}</p>
        <div class="footer-links">
            <a href="https://github.com/code-is-cheap/show-me-the-talk" target="_blank">
                <i class="fab fa-github"></i> GitHub
            </a>
            <a href="#" onclick="window.print(); return false;">
                <i class="fas fa-print"></i> Print
            </a>
            <a href="#" onclick="exportDashboard(); return false;">
                <i class="fas fa-download"></i> Export
            </a>
        </div>
    </footer>`;
    }

    /**
     * Generate all JavaScript code
     */
    private generateScripts(report: AnalyticsReport): string {
        return `<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-cloud@1.2.7/build/d3.layout.cloud.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/countup.js@2.8.0/dist/countUp.umd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        // Theme management
        function toggleTheme() {
            const html = document.documentElement;
            const currentTheme = html.getAttribute('data-theme');
            const icon = document.querySelector('.theme-toggle i');

            if (currentTheme === 'light' || currentTheme === 'auto') {
                html.setAttribute('data-theme', 'dark');
                icon.className = 'fas fa-sun';
                localStorage.setItem('theme', 'dark');
            } else {
                html.setAttribute('data-theme', 'light');
                icon.className = 'fas fa-moon';
                localStorage.setItem('theme', 'light');
            }
        }

        // Initialize theme
        function initTheme() {
            const savedTheme = localStorage.getItem('theme') || '${this.options.theme}';
            document.documentElement.setAttribute('data-theme', savedTheme);
            const icon = document.querySelector('.theme-toggle i');
            if (savedTheme === 'dark') {
                icon.className = 'fas fa-sun';
            }
        }

        // Chart.js default configuration
        Chart.defaults.font.family = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif';
        Chart.defaults.plugins.legend.display = true;
        Chart.defaults.plugins.tooltip.enabled = true;

        // Initialize Tech Stack Chart
        function initTechStackChart() {
            if (!window.techStackData) return;

            const ctx = document.getElementById('techStackChart');
            if (!ctx) return;

            // Sort data to get top 3
            const dataWithIndex = window.techStackData.data.map((value, index) => ({
                value,
                label: window.techStackData.labels[index],
                index
            })).sort((a, b) => b.value - a.value);

            // Add medal emojis to top 3
            const medals = ['🥇', '🥈', '🥉'];
            const labelsWithMedals = window.techStackData.labels.map((label, index) => {
                const rank = dataWithIndex.findIndex(item => item.index === index);
                if (rank >= 0 && rank < 3) {
                    return \`\${medals[rank]} \${label}\`;
                }
                return label;
            });

            // Color top 3 with vibrant colors, others in gray
            const TABLEAU10 = ['#4E79A7', '#F28E2B', '#E15759'];
            const backgroundColors = window.techStackData.data.map((value, index) => {
                const rank = dataWithIndex.findIndex(item => item.index === index);
                if (rank >= 0 && rank < 3) {
                    return TABLEAU10[rank] + 'D9'; // 85% opacity
                }
                return 'rgba(115, 115, 115, 0.5)';
            });
            const borderColors = window.techStackData.data.map((value, index) => {
                const rank = dataWithIndex.findIndex(item => item.index === index);
                if (rank >= 0 && rank < 3) {
                    return TABLEAU10[rank];
                }
                return '#737373';
            });

            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labelsWithMedals,
                    datasets: [{
                        label: 'Usage Count',
                        data: window.techStackData.data,
                        backgroundColor: backgroundColors,
                        borderColor: borderColors,
                        borderWidth: 2,
                        borderRadius: 6
                    }]
                },
                options: {
                    indexAxis: 'y',  // Horizontal bar chart (more professional)
                    responsive: true,
                    maintainAspectRatio: false,
                    animation: {
                        duration: 1500,
                        easing: 'easeOutQuart'
                    },
                    plugins: {
                        legend: { display: false },
                        title: { display: false },
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    const label = context.label.replace(/^[🥇🥈🥉] /, '');
                                    const value = context.parsed.x;
                                    return \`\${label}: \${value} conversations\`;
                                }
                            },
                            backgroundColor: 'rgba(0, 0, 0, 0.8)',
                            padding: 12
                        }
                    },
                    scales: {
                        x: {
                            beginAtZero: true,
                            ticks: {
                                precision: 0,
                                font: { size: 12 }
                            },
                            grid: {
                                color: 'rgba(0, 0, 0, 0.05)'
                            }
                        },
                        y: {
                            grid: {
                                display: false
                            },
                            ticks: {
                                font: {
                                    size: 13,
                                    weight: '500'
                                }
                            }
                        }
                    }
                }
            });
        }

        // Initialize Task Distribution Chart
        function initTaskDistributionChart() {
            if (!window.taskDistributionData) return;

            const ctx = document.getElementById('taskDistributionChart');
            if (!ctx) return;

            // Tableau10 color palette (professional, colorblind-friendly)
            const TABLEAU10 = [
                '#4E79A7',  // Blue
                '#F28E2B',  // Orange
                '#E15759',  // Red
                '#76B7B2',  // Teal
                '#59A14F',  // Green
                '#EDC948',  // Yellow
                '#B07AA1',  // Purple
                '#FF9DA7',  // Pink
                '#9C755F',  // Brown
                '#BAB0AC',  // Gray
            ];

            // Get colors for data (with 90% opacity for better vibrancy)
            const dataCount = window.taskDistributionData.labels.length;
            const colors = TABLEAU10.slice(0, Math.min(dataCount, 10)).map(c => c + 'E6');

            // Calculate total and find largest value
            const total = window.taskDistributionData.data.reduce((a, b) => a + b, 0);
            const maxValue = Math.max(...window.taskDistributionData.data);
            const maxIndex = window.taskDistributionData.data.indexOf(maxValue);
            const maxPercentage = ((maxValue / total) * 100).toFixed(1);
            const maxLabel = window.taskDistributionData.labels[maxIndex];

            // Custom plugin for center text
            const centerTextPlugin = {
                id: 'centerText',
                afterDraw: (chart) => {
                    const { ctx, chartArea: { width, height } } = chart;
                    ctx.save();

                    const centerX = width / 2;
                    const centerY = height / 2;

                    // Main percentage
                    ctx.font = 'bold 48px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
                    ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--text-primary');
                    ctx.textAlign = 'center';
                    ctx.textBaseline = 'middle';
                    ctx.fillText(\`\${maxPercentage}%\`, centerX, centerY - 15);

                    // Label
                    ctx.font = '14px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
                    ctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--text-secondary');
                    ctx.fillText(maxLabel, centerX, centerY + 25);

                    ctx.restore();
                }
            };

            new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: window.taskDistributionData.labels,
                    datasets: [{
                        data: window.taskDistributionData.data,
                        backgroundColor: colors,
                        borderWidth: 3,
                        borderColor: getComputedStyle(document.documentElement).getPropertyValue('--bg-elevated'),
                        hoverOffset: 15
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    cutout: '65%',  // Larger cutout for center text
                    animation: {
                        animateRotate: true,
                        animateScale: true,
                        duration: 2000,
                        easing: 'easeOutCubic'
                    },
                    plugins: {
                        legend: {
                            position: 'right',
                            labels: {
                                usePointStyle: true,
                                padding: 16,
                                font: {
                                    family: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
                                    size: 14
                                },
                                boxWidth: 12,
                                boxHeight: 12
                            }
                        },
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    const label = context.label || '';
                                    const value = context.parsed;
                                    const total = context.dataset.data.reduce((a, b) => a + b, 0);
                                    const percentage = ((value / total) * 100).toFixed(1);
                                    return \`\${label}: \${value} conversations (\${percentage}%)\`;
                                }
                            },
                            backgroundColor: 'rgba(0, 0, 0, 0.8)',
                            padding: 12,
                            titleFont: { size: 14 },
                            bodyFont: { size: 13 }
                        }
                    }
                },
                plugins: [centerTextPlugin]
            });
        }

        // Initialize Timeline Chart
        function initTimelineChart() {
            if (!window.timelineData) return;

            const ctx = document.getElementById('timelineChart');
            if (!ctx) return;

            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: window.timelineData.labels,
                    datasets: [
                        {
                            label: 'Conversations',
                            data: window.timelineData.conversations,
                            borderColor: '#0070f3',
                            backgroundColor: 'rgba(0, 112, 243, 0.08)',
                            tension: 0.3,
                            fill: true,
                            borderWidth: 2
                        },
                        {
                            label: 'Messages',
                            data: window.timelineData.messages,
                            borderColor: '#404040',  // Darker gray for better contrast
                            backgroundColor: 'rgba(64, 64, 64, 0.08)',
                            tension: 0.3,
                            fill: true,
                            borderWidth: 2
                        }
                    ]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    interaction: {
                        mode: 'index',
                        intersect: false
                    },
                    plugins: {
                        legend: {
                            position: 'top',
                            labels: {
                                usePointStyle: true,
                                padding: 12
                            }
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: true,
                            grid: {
                                color: 'rgba(0, 0, 0, 0.05)'
                            }
                        },
                        x: {
                            grid: {
                                display: false
                            }
                        }
                    }
                }
            });
        }

        // Tableau10 color palette for word cloud
        const TABLEAU10_COLORS = [
            '#4E79A7', '#F28E2B', '#E15759', '#76B7B2', '#59A14F',
            '#EDC948', '#B07AA1', '#FF9DA7', '#9C755F', '#BAB0AC'
        ];

        // Get color based on theme and word index
        function getWordCloudColor(index, weight, theme) {
            const normalized = weight;

            if (theme === 'tableau10') {
                // Vibrant: Cycle through Tableau10 colors
                return TABLEAU10_COLORS[index % TABLEAU10_COLORS.length];
            } else if (theme === 'gradient') {
                // Gradient: Orange to purple based on weight
                const hue = 30 + (normalized * 250); // 30° (orange) -> 280° (purple)
                const saturation = 85 + (normalized * 15); // 85% -> 100%
                const lightness = 55 - (normalized * 20); // 55% -> 35%
                return \`hsl(\${hue}, \${saturation}%, \${lightness}%)\`;
            } else {
                // Monochrome: Blue gradient
                const lightness = 70 - normalized * 30; // 70% (light) -> 40% (dark)
                return \`hsl(214, 100%, \${lightness}%)\`;
            }
        }

        // Initialize Word Cloud
        function initWordCloud() {
            if (!window.wordCloudData) return;

            const canvas = document.getElementById('wordCloudCanvas');
            if (!canvas) return;

            const ctx = canvas.getContext('2d');
            const width = canvas.offsetWidth;
            const height = 400;
            canvas.width = width;
            canvas.height = height;

            // Simple word cloud rendering on canvas
            ctx.clearRect(0, 0, width, height);
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';

            const words = window.wordCloudData.slice(0, 30);

            // Calculate weight range for color mapping
            const weights = words.map(w => w.weight);
            const minWeight = Math.min(...weights);
            const maxWeight = Math.max(...weights);

            const centerX = width / 2;
            const centerY = height / 2;

            const theme = window.currentWordCloudTheme || 'tableau10';

            words.forEach((word, i) => {
                const angle = (Math.PI * 2 * i) / words.length;
                const radius = 80 + Math.random() * 100;
                const x = centerX + Math.cos(angle) * radius;
                const y = centerY + Math.sin(angle) * radius;

                // Normalize weight for color calculation
                const normalized = (word.weight - minWeight) / (maxWeight - minWeight || 1);

                ctx.font = \`\${word.size}px -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif\`;
                ctx.fillStyle = getWordCloudColor(i, normalized, theme);
                ctx.fillText(word.text, x, y);
            });
        }

        // Change word cloud theme
        function changeWordCloudTheme(theme) {
            window.currentWordCloudTheme = theme;

            // Update button states
            document.querySelectorAll('.theme-btn').forEach(btn => {
                if (btn.getAttribute('data-theme') === theme) {
                    btn.style.background = 'var(--color-primary)';
                    btn.style.color = '#ffffff';
                    btn.style.borderColor = 'var(--color-primary)';
                } else {
                    btn.style.background = 'var(--bg-elevated)';
                    btn.style.color = 'var(--text-primary)';
                    btn.style.borderColor = 'var(--border)';
                }
            });

            // Re-render word cloud
            initWordCloud();
        }

        // Export functions
        function exportWordCloud() {
            const canvas = document.getElementById('wordCloudCanvas');
            if (!canvas) return;

            const link = document.createElement('a');
            link.download = 'word-cloud.png';
            link.href = canvas.toDataURL();
            link.click();
        }

        function exportDashboard() {
            window.print();
        }

        // Initialize CountUp animations for stat cards
        function initCountUpAnimations() {
            document.querySelectorAll('[data-countup]').forEach(el => {
                const value = parseFloat(el.getAttribute('data-countup'));
                const decimals = parseInt(el.getAttribute('data-decimals') || '0');

                if (!isNaN(value)) {
                    const countUp = new countUp.CountUp(el, value, {
                        duration: 2,
                        separator: ',',
                        decimal: '.',
                        decimalPlaces: decimals,
                        useEasing: true,
                        useGrouping: true
                    });
                    countUp.start();
                }
            });
        }

        // Initialize Heatmap
        function initHeatmap() {
            if (!window.heatmapData) return;

            const container = document.getElementById('heatmapContainer');
            if (!container) return;

            // Create grid
            const grid = document.createElement('div');
            grid.className = 'heatmap-grid';

            // Group cells by week for column layout
            const weeks = new Map();
            for (const cell of window.heatmapData) {
                if (!weeks.has(cell.weekNumber)) {
                    weeks.set(cell.weekNumber, []);
                }
                weeks.get(cell.weekNumber).push(cell);
            }

            // Render cells (7 rows × N weeks columns)
            const sortedWeeks = Array.from(weeks.values()).sort((a, b) => {
                const dateA = new Date(a[0].date);
                const dateB = new Date(b[0].date);
                return dateA - dateB;
            });

            for (const week of sortedWeeks) {
                // Sort days in week by dayOfWeek
                week.sort((a, b) => a.dayOfWeek - b.dayOfWeek);

                // Fill missing days with empty cells
                const filledWeek = [];
                for (let dow = 1; dow <= 7; dow++) {
                    const cell = week.find(c => c.dayOfWeek === dow);
                    if (cell) {
                        filledWeek.push(cell);
                    } else {
                        filledWeek.push({ date: '', count: 0, level: 0, dayOfWeek: dow });
                    }
                }

                for (const cell of filledWeek) {
                    const cellEl = document.createElement('div');
                    cellEl.className = 'heatmap-cell';
                    cellEl.setAttribute('data-level', cell.level);
                    cellEl.setAttribute('data-date', cell.date);
                    cellEl.setAttribute('data-count', cell.count);

                    if (cell.count > 0) {
                        cellEl.title = \`\${cell.date}: \${cell.count} conversation\${cell.count > 1 ? 's' : ''}\`;
                    }

                    grid.appendChild(cellEl);
                }
            }

            container.appendChild(grid);
        }

        // Wrapped Story Functions
        let wrappedSwiper;

        function openWrappedStory() {
            const modal = document.getElementById('wrappedModal');
            if (modal) {
                modal.classList.add('active');
                document.body.style.overflow = 'hidden';

                // Initialize Swiper if not already initialized
                if (!wrappedSwiper) {
                    wrappedSwiper = new Swiper('.wrapped-swiper', {
                        direction: 'vertical',
                        loop: false,
                        pagination: {
                            el: '.swiper-pagination',
                            clickable: true
                        },
                        keyboard: {
                            enabled: true
                        },
                        mousewheel: {
                            enabled: true
                        }
                    });
                }
            }
        }

        function closeWrappedStory() {
            const modal = document.getElementById('wrappedModal');
            if (modal) {
                modal.classList.remove('active');
                document.body.style.overflow = '';
                if (wrappedSwiper) {
                    wrappedSwiper.slideTo(0);
                }
            }
        }

        function shareToTwitter() {
            const text = encodeURIComponent("Check out my coding journey with Claude! #ClaudeWrapped");
            const url = \`https://twitter.com/intent/tweet?text=\${text}\`;
            window.open(url, '_blank');
        }

        function shareToLinkedIn() {
            const text = encodeURIComponent("Check out my coding journey with Claude!");
            const url = \`https://www.linkedin.com/sharing/share-offsite/?url=\${encodeURIComponent(window.location.href)}\`;
            window.open(url, '_blank');
        }

        function downloadWrapped() {
            alert('Download functionality coming soon! For now, take a screenshot of your favorite card.');
        }

        // Initialize all
        window.addEventListener('DOMContentLoaded', () => {
            initTheme();
            initCountUpAnimations();
            initHeatmap();
            initTechStackChart();
            initTaskDistributionChart();
            initTimelineChart();
            initWordCloud();

            // Set initial theme button state for word cloud
            changeWordCloudTheme('tableau10');
        });

        // Re-render word cloud on resize
        window.addEventListener('resize', () => {
            setTimeout(initWordCloud, 100);
        });
    </script>`;
    }

    /**
     * Escape HTML to prevent XSS
     */
    private escapeHtml(text: string): string {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }
}
